jdbc:
  driverClassName: org.h2.Driver
  url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
  username: sa
  password: sa
notification:
  email-subject: Auto notification
  sender-email: robot@somecompany.com
features:
  active:
    persistence: on
    multiple-senders: off
